name: my_flutter_app
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Additional dependencies for navigation and forms
  provider: ^6.0.5
  fluttertoast: ^8.2.1

flutter:
  uses-material-design: true
